alg_name: "FINE"
model_name: "./pretrained_model/gpt-j-6b"
device: 0
epochs: 50
lr: 1e-3
gamma: 0.1
beta: 10
alpha: 1
neuron_num: 5
early_stop_prob: 0.9
last_layer: 3
rewrite_module_tmp: "transformer.h.{}.mlp.fc_out"
layer_module_tmp: "transformer.h.{}"
mlp_module_tmp: "transformer.h.{}.mlp"
attn_module_tmp: "transformer.h.{}.attn"
ln_f_module: "transformer.ln_f"
lm_head_module: "lm_head"
model_parallel: true
fp16: true





